### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by benjamingr** [tc39/proposal-flatMap#36]
Hey, can you please add a readme about the state/etc which users can monitor for state level changes :)?

**Comment by michaelficarra** [comment]
@benjamingr The current status of all active proposals can be found on the [proposal status page](https://github.com/tc39/proposals).

This proposal is currently stage 1. I will probably look to advance it to stage 2 at the next meeting later this month.

**Comment by benjamingr** [comment]
Thanks @michaelficarra, if you could update the repository after the meeting and make the information about the proposal status more accessible I would appreciate it.

**Comment by ljharb** [comment]
@benjamingr it's certainly great for champions to update their own repos, but the proposals page is the source of truth - if it says stage 1, it doesn't matter what the individual repo claims it is.
