### ISSUE TITLE
stage 2 assigned reviewer sign-off

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-flatMap#44]
As a formality, just getting written sign-off in this issue from the assigned reviewers (necessary for the planned advancement to stage 3 at the next meeting)

- [x] @ljharb 
- [x] @rwaldron 
- [ ] @spectranaut

**Comment by ljharb** [comment]
Signed off! The spec steps work well in both of my polyfills as well:
 - https://github.com/es-shims/Array.prototype.flatten
 - https://github.com/es-shims/Array.prototype.flatMap
