### ISSUE TITLE
test262 tests

### ISSUE THREAD

**Issue by evilpie** [tc39/proposal-flatMap#51]
I am looking into implementing this feature in Firefox. ([bug 1421398](https://bugzilla.mozilla.org/show_bug.cgi?id=1421398)) Are there any tests in-flight for this yet?

**Comment by michaelficarra** [comment]
Sorry, there's no test262 tests yet. I was planning on working on it next week if nobody had beaten me to it. It'd be a really good opportunity for a new contributor.

**Comment by Jayflux** [comment]
I'm up for writing some @michaelficarra

**Comment by michaelficarra** [comment]
@Jayflux one of my co-workers (@shilpi3) wanted to try her hand at it, and already started yesterday. She should be done today. Sorry!

**Comment by Jayflux** [comment]
@michaelficarra no worries!

**Comment by michaelficarra** [comment]
@evilpie Initial test262 tests are now available (see https://github.com/tc39/test262/pull/1388). We may add some which exercise the handling of more exotic values in the future, but these should be sufficient to get started.

**Comment by montogeek** [comment]
@michaelficarra What else have to be done to push it forward to Stage 4?

**Comment by michaelficarra** [comment]
@montogeek We have to see at least 2 distinct compatible implementations which pass the test262 tests. Expanding the test262 tests as I mentioned above might help that along. But at this point it's up to the implementors. Maybe let them know you're looking forward to using this feature.

**Comment by evilpie** [comment]
Fixed by https://github.com/tc39/test262/pull/1388
