### ISSUE TITLE
Update gh-pages

### ISSUE THREAD

**Issue by evilpie** [tc39/proposal-flatMap#53]
I just implemented an older version of this proposal, because https://tc39.github.io/proposal-flatMap/ wasn't updated.

**Comment by michaelficarra** [comment]
Oh no! Sorry about that. Fixed.

**Comment by ljharb** [comment]
If you switch the setting for gh-pages to master, you’ll never have to manually keep them in sync, and you can delete the gh-pages branch entirely.

**Comment by michaelficarra** [comment]
@ljharb You can still fail to run ecmarkup. Also, I prefer this as I get to make edits through the GH web interface. In some of my other proposals, Travis automatically publishes anything that lands on master, but I was too lazy to set it up for this repo.

**Comment by ljharb** [comment]
ah, that is true.
