### ISSUE TITLE
.d.ts proposal inaccurate

### ISSUE THREAD

**Issue by shicks** [tc39/proposal-flatMap#76]
The proposed .d.ts for `Array.prototype.flat` is much less accurate than it could be.

The following is more in line with the implementation:
```
type Unwrap<X> = X extends (infer Y)[] ? Y : X;

interface Array<T> {
    // ...
    flat(depth: 2): Unwrap<Unwrap<Unwrap<this>>>[];
    flat(depth?: 1): Unwrap<Unwrap<this>>[];
    flat(depth: 0): Unwrap<this>[];
    flat(depth?: number): any[];
}
```

This allows correctly inferring that calling flat(1) on, e.g., `(number | number[][])[]` returns `(number | number[])[]`.

**Comment by bakkot** [comment]
That file is no longer particularly relevant. (Nor is this repository, for that matter.) TypeScript [has its own definitions](https://github.com/Microsoft/TypeScript/blob/2f9218f346bbc606cccc4aebfca1c2c4f3167fee/lib/lib.esnext.array.d.ts#L137-L222), and any issues with them should be raised with the TypeScript team, not here.
